/*
SQLyog Community v13.3.0 (64 bit)
MySQL - 8.0.44 : Database - fusioncms
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `hangman_games` */

DROP TABLE IF EXISTS `hangman_games`;

CREATE TABLE `hangman_games` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL DEFAULT '0',
  `session_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `last_activity` datetime NOT NULL,
  `score` int NOT NULL DEFAULT '0',
  `health` int NOT NULL DEFAULT '6',
  `word_id` int NOT NULL DEFAULT '0',
  `difficulty` tinyint(1) NOT NULL DEFAULT '1',
  `letters` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `rewarded` tinyint(1) NOT NULL DEFAULT '0',
  `reward_vp` int NOT NULL DEFAULT '0',
  `reward_dp` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `session_id` (`session_id`),
  KEY `rewarded` (`rewarded`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `hangman_games` */

/*Table structure for table `hangman_highscore` */

DROP TABLE IF EXISTS `hangman_highscore`;

CREATE TABLE `hangman_highscore` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `score` int NOT NULL DEFAULT '0',
  `games` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `hangman_highscore` */

/*Table structure for table `hangman_rewards` */

DROP TABLE IF EXISTS `hangman_rewards`;

CREATE TABLE `hangman_rewards` (
  `id` int NOT NULL AUTO_INCREMENT,
  `game_id` int NOT NULL,
  `user_id` int NOT NULL,
  `vote_points` int NOT NULL DEFAULT '0',
  `donate_points` int NOT NULL DEFAULT '0',
  `difficulty` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `game_id` (`game_id`),
  KEY `user_id` (`user_id`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `hangman_rewards` */

/*Table structure for table `hangman_words` */

DROP TABLE IF EXISTS `hangman_words`;

CREATE TABLE `hangman_words` (
  `id` int NOT NULL AUTO_INCREMENT,
  `text` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `difficulty` tinyint(1) NOT NULL DEFAULT '1',
  `locale` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'english',
  PRIMARY KEY (`id`),
  KEY `difficulty_locale` (`difficulty`,`locale`)
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `hangman_words` */

insert  into `hangman_words`(`id`,`text`,`difficulty`,`locale`) values 
(1,'Murloc',1,'english'),
(2,'Kobold',1,'english'),
(3,'Gnoll',1,'english'),
(4,'Worgen',1,'english'),
(5,'Tauren',1,'english'),
(6,'Draenei',1,'english'),
(7,'Goblin',1,'english'),
(8,'Gnome',1,'english'),
(9,'Orc',1,'english'),
(10,'Troll',1,'english'),
(11,'Horde',1,'english'),
(12,'Alliance',1,'english'),
(13,'Azeroth',1,'english'),
(14,'Durotar',1,'english'),
(15,'Elwynn Forest',1,'english'),
(16,'Goldshire',1,'english'),
(17,'Stormwind',1,'english'),
(18,'Orgrimmar',1,'english'),
(19,'Darnassus',1,'english'),
(20,'Ironforge',1,'english'),
(21,'Thunder Bluff',2,'english'),
(22,'Silvermoon City',2,'english'),
(23,'Undercity',2,'english'),
(24,'Darkmoon Faire',2,'english'),
(25,'Deadmines',2,'english'),
(26,'Ragefire Chasm',2,'english'),
(27,'Scarlet Monastery',2,'english'),
(28,'Blackrock Depths',2,'english'),
(29,'Stranglethorn Vale',2,'english'),
(30,'Burning Steppes',2,'english'),
(31,'Western Plaguelands',2,'english'),
(32,'Eastern Plaguelands',2,'english'),
(33,'Felwood',2,'english'),
(34,'Feralas',2,'english'),
(35,'Dustwallow Marsh',2,'english'),
(36,'Arathi Highlands',2,'english'),
(37,'Thousand Needles',2,'english'),
(38,'Hinterlands',2,'english'),
(39,'Alterac Mountains',2,'english'),
(40,'Swamp of Sorrows',2,'english'),
(41,'Onyxia\'s Lair',3,'english'),
(42,'Molten Core',3,'english'),
(43,'Blackwing Lair',3,'english'),
(44,'Ahn\'Qiraj',3,'english'),
(45,'Naxxramas',3,'english'),
(46,'Karazhan',3,'english'),
(47,'Icecrown Citadel',3,'english'),
(48,'Dragon Soul',3,'english'),
(49,'Throne of Thunder',3,'english'),
(50,'Siege of Orgrimmar',3,'english'),
(51,'Caverns of Time',3,'english'),
(52,'Emerald Nightmare',3,'english'),
(53,'Antorus the Burning Throne',3,'english'),
(54,'Zul\'Gurub',3,'english'),
(55,'Zul\'Aman',3,'english'),
(56,'Gnomeregan',3,'english'),
(57,'Ulduar',3,'english'),
(58,'Sunwell Plateau',3,'english'),
(59,'Black Temple',3,'english'),
(60,'Serpentshrine Cavern',3,'english'),
(61,'Murloc',1,'german'),
(62,'Kobold',1,'german'),
(63,'Gnoll',1,'german'),
(64,'Worgen',1,'german'),
(65,'Tauren',1,'german'),
(66,'Draenei',1,'german'),
(67,'Goblin',1,'german'),
(68,'Gnom',1,'german'),
(69,'Ork',1,'german'),
(70,'Troll',1,'german'),
(71,'Horde',1,'german'),
(72,'Allianz',1,'german'),
(73,'Azeroth',1,'german'),
(74,'Durotar',1,'german'),
(75,'Goldhain',1,'german'),
(76,'Sturmwind',1,'german'),
(77,'Orgrimmar',1,'german'),
(78,'Darnassus',1,'german'),
(79,'Eisenschmiede',1,'german'),
(80,'Elwynn',1,'german'),
(81,'Donnerfels',2,'german'),
(82,'Silbermond',2,'german'),
(83,'Unterstadt',2,'german'),
(84,'Dunkelmond-Jahrmarkt',2,'german'),
(85,'Todesminen',2,'german'),
(86,'Flammenschlund',2,'german'),
(87,'Scholomance',2,'german'),
(88,'Scharlachrotes Kloster',2,'german'),
(89,'Schwarzfelstiefen',2,'german'),
(90,'Schlingendorntal',2,'german'),
(91,'Brennende Steppe',2,'german'),
(92,'Westliche Pestländer',2,'german'),
(93,'Östliche Pestländer',2,'german'),
(94,'Teufelswald',2,'german'),
(95,'Feralas',2,'german'),
(96,'Sumpfland',2,'german'),
(97,'Arathihochland',2,'german'),
(98,'Tausend Nadeln',2,'german'),
(99,'Hinterland',2,'german'),
(100,'Sümpfe des Elends',2,'german'),
(101,'Onyxias Hort',3,'german'),
(102,'Geschmolzener Kern',3,'german'),
(103,'Pechschwingenhort',3,'german'),
(104,'Ahn\'Qiraj',3,'german'),
(105,'Naxxramas',3,'german'),
(106,'Karazhan',3,'german'),
(107,'Eiskronenzitadelle',3,'german'),
(108,'Drachenseele',3,'german'),
(109,'Thron des Donners',3,'german'),
(110,'Schlacht um Orgrimmar',3,'german'),
(111,'Höhlen der Zeit',3,'german'),
(112,'Smaragdgrüner Alptraum',3,'german'),
(113,'Antorus der Brennende Thron',3,'german'),
(114,'Zul\'Gurub',3,'german'),
(115,'Zul\'Aman',3,'german'),
(116,'Gnomeregan',3,'german'),
(117,'Ulduar',3,'german'),
(118,'Sonnenbrunnenplateau',3,'german'),
(119,'Der Schwarze Tempel',3,'german'),
(120,'Höhlen des Schlangenschreins',3,'german'),
(121,'Murloc',1,'english'),
(122,'Kobold',1,'english'),
(123,'Gnoll',1,'english'),
(124,'Worgen',1,'english'),
(125,'Tauren',1,'english'),
(126,'Draenei',1,'english'),
(127,'Goblin',1,'english'),
(128,'Gnome',1,'english'),
(129,'Orc',1,'english'),
(130,'Troll',1,'english'),
(131,'Horde',1,'english'),
(132,'Alliance',1,'english'),
(133,'Azeroth',1,'english'),
(134,'Durotar',1,'english'),
(135,'Pandaria',1,'english'),
(136,'Thunder Bluff',2,'english'),
(137,'Silvermoon City',2,'english'),
(138,'Undercity',2,'english'),
(139,'Darkmoon Faire',2,'english'),
(140,'Deadmines',2,'english'),
(141,'Ragefire Chasm',2,'english'),
(142,'Scarlet Monastery',2,'english'),
(143,'Blackrock Depths',2,'english'),
(144,'Stranglethorn Vale',2,'english'),
(145,'Burning Steppes',2,'english'),
(146,'Western Plaguelands',2,'english'),
(147,'Eastern Plaguelands',2,'english'),
(148,'Grizzly Hills',2,'english'),
(149,'Howling Fjord',2,'english'),
(150,'Azuremyst Isle',2,'english'),
(151,'Icecrown Citadel',3,'english'),
(152,'Blackwing Lair',3,'english'),
(153,'Molten Core',3,'english'),
(154,'Temple of Ahn Qiraj',3,'english'),
(155,'Throne of Thunder',3,'english'),
(156,'Siege of Orgrimmar',3,'english'),
(157,'Sunwell Plateau',3,'english'),
(158,'Serpentshrine Cavern',3,'english'),
(159,'Trial of the Crusader',3,'english'),
(160,'Vault of Archavon',3,'english'),
(161,'Halls of Reflection',3,'english'),
(162,'Grim Batol',3,'english'),
(163,'Mogu Shan Vaults',3,'english'),
(164,'The Nighthold',3,'english'),
(165,'Tomb of Sargeras',3,'english'),
(166,'Lich King Arthas',4,'english'),
(167,'Illidan Stormrage',4,'english'),
(168,'Deathwing the Destroyer',4,'english'),
(169,'Sargeras the Dark Titan',4,'english'),
(170,'Sylvanas Windrunner',4,'english'),
(171,'Jaina Proudmoore',4,'english'),
(172,'Anduin Wrynn',4,'english'),
(173,'Khadgar the Archmage',4,'english'),
(174,'Malfurion Stormrage',4,'english'),
(175,'Tyrande Whisperwind',4,'english'),
(176,'Garrosh Hellscream',4,'english'),
(177,'Nerzhul the Lich King',4,'english'),
(178,'Kiljaeden the Deceiver',4,'english'),
(179,'Yogg Saron',4,'english'),
(180,'Nerubian Empire',4,'english'),
(181,'Amirdrassil the Dream Hope',5,'english'),
(182,'Aberrus the Shadowed Crucible',5,'english'),
(183,'Sepulcher of the First Ones',5,'english'),
(184,'Sanctum of Domination',5,'english'),
(185,'Castle Nathria',5,'english'),
(186,'Ny Alotha the Waking City',5,'english'),
(187,'Battle of Dazaralor',5,'english'),
(188,'Antorus the Burning Throne',5,'english'),
(189,'Tomb of Sargeras',5,'english'),
(190,'Emerald Nightmare',5,'english'),
(191,'Black Temple of Illidan',5,'english'),
(192,'Dragonflight Isles',5,'english'),
(193,'The War Within',5,'english'),
(194,'Khaz Algar',5,'english'),
(195,'Isle of Dorn',5,'english'),
(196,'Murloc',1,'german'),
(197,'Kobold',1,'german'),
(198,'Gnoll',1,'german'),
(199,'Worgen',1,'german'),
(200,'Tauren',1,'german'),
(201,'Draenei',1,'german'),
(202,'Goblin',1,'german'),
(203,'Gnom',1,'german'),
(204,'Ork',1,'german'),
(205,'Troll',1,'german'),
(206,'Horde',1,'german'),
(207,'Allianz',1,'german'),
(208,'Azeroth',1,'german'),
(209,'Durotar',1,'german'),
(210,'Pandaria',1,'german'),
(211,'Donnerfels',2,'german'),
(212,'Silbermond',2,'german'),
(213,'Unterstadt',2,'german'),
(214,'Dunkelmond Jahrmarkt',2,'german'),
(215,'Todesminen',2,'german'),
(216,'Flammenschlund',2,'german'),
(217,'Scharlachrotes Kloster',2,'german'),
(218,'Schwarzfelstiefen',2,'german'),
(219,'Schlingendorntal',2,'german'),
(220,'Brennende Steppe',2,'german'),
(221,'Westliche Pestlaender',2,'german'),
(222,'Oestliche Pestlaender',2,'german'),
(223,'Graue Huegel',2,'german'),
(224,'Heulender Fjord',2,'german'),
(225,'Azurmythosinsel',2,'german'),
(226,'Eiskronenzitadelle',3,'german'),
(227,'Pechschwingenhort',3,'german'),
(228,'Geschmolzener Kern',3,'german'),
(229,'Tempel von Ahn Qiraj',3,'german'),
(230,'Thron des Donners',3,'german'),
(231,'Schlacht um Orgrimmar',3,'german'),
(232,'Sonnenbrunnenplateau',3,'german'),
(233,'Höhle des Schlangenschreins',3,'german'),
(234,'Pruefung des Kreuzfahrers',3,'german'),
(235,'Archavons Kammer',3,'german'),
(236,'Hallen der Reflexion',3,'german'),
(237,'Grimm Batol',3,'german'),
(238,'Mogu Shan Gewoelbe',3,'german'),
(239,'Die Nachtfestung',3,'german'),
(240,'Grabmal des Sargeras',3,'german'),
(241,'Arthas der Lichkoenig',4,'german'),
(242,'Illidan Sturmgrimm',4,'german'),
(243,'Todesschwinge der Zerstoerer',4,'german'),
(244,'Sargeras der Dunkle Titan',4,'german'),
(245,'Sylvanas Windlaeufer',4,'german'),
(246,'Jaina Prachtmeer',4,'german'),
(247,'Anduin Wrynn',4,'german'),
(248,'Khadgar der Erzmagier',4,'german'),
(249,'Malfurion Sturmgrimm',4,'german'),
(250,'Tyrande Wisperwind',4,'german'),
(251,'Garrosh Höllschrei',4,'german'),
(252,'Nerzhul der Lichkoenig',4,'german'),
(253,'Kiljaeden der Betrueger',4,'german'),
(254,'Yogg Saron',4,'german'),
(255,'Nerubisches Imperium',4,'german'),
(256,'Amirdrassil die Hoffnung des Traums',5,'german'),
(257,'Aberrus die Schattenkammer',5,'german'),
(258,'Mausoleum der Ersten',5,'german'),
(259,'Sanktum der Herrschaft',5,'german'),
(260,'Schloss Nathria',5,'german'),
(261,'Ny Alotha die Erwachte Stadt',5,'german'),
(262,'Schlacht von Dazaralor',5,'german'),
(263,'Antorus der Brennende Thron',5,'german'),
(264,'Grabmal des Sargeras',5,'german'),
(265,'Smaragdgrüner Alptraum',5,'german'),
(266,'Schwarzer Tempel von Illidan',5,'german'),
(267,'Dracheninseln',5,'german'),
(268,'Der Innere Krieg',5,'german'),
(269,'Khaz Algar',5,'german'),
(270,'Insel von Dorn',5,'german');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
